# Generated by Django 2.1.7 on 2019-04-29 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('order', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blog.Order')),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.product')),
            ],
            options={
                'verbose_name': 'Единица заказа',
                'verbose_name_plural': 'Единицы заказов',
            },
        ),
        migrations.RemoveField(
            model_name='myorderitem',
            name='prod',
        ),
        migrations.RemoveField(
            model_name='myordermodel',
            name='items',
        ),
        migrations.DeleteModel(
            name='myOrderItem',
        ),
        migrations.DeleteModel(
            name='myOrderModel',
        ),
    ]
